set(temperature_sensor_controller_MESSAGE_FILES "/home/tomer/cogrob_project/src/ros_controllers/temperature_sensor_controller/msg/ActuatorTemperatureState.msg")
set(temperature_sensor_controller_SERVICE_FILES "")
